use treinamento
SET DATEFORMAT dmy;

BEGIN TRANSACTION
select * from REQUEST

update REQUEST set DTDELIVER = (DTDELIVER + 30) WHERE DTREQUEST IN (SELECT r.DTREQUEST FROM REQUEST as r WHERE (r.DTREQUEST - r.DTDELIVER) < 10 
									AND CDCUSTOMER IN (SELECT R.CDCUSTOMER FROM CUSTOMER as c INNER JOIN REQUEST as r ON c.CDCUSTOMER = r.CDCUSTOMER
																	group by r.CDCUSTOMER
																	having sum(r.VLTOTAL) < 10000)) 
select * from REQUEST
ROLLBACK
