use treinamento

BEGIN TRANSACTION

DELETE FROM SUPPLIER WHERE CDSUPPLIER IN
	(SELECT s.CDSUPPLIER
		FROM SUPPLIER as s left join PRODUCT as p ON s.CDSUPPLIER = p.CDSUPPLIER
		group by s.CDSUPPLIER
		having count(p.CDPRODUCT) = 0)

ROLLBACK

