CREATE DATABASE DESAFIOSQL;
USE DESAFIOSQL;


CREATE TABLE PRODUCTREQUEST (

 	CDREQUEST INT NOT NULL,
	CDPRODUCT INT NOT NULL,
	QTAMOUNT INTEGER,
	VLUNITARY NUMERIC(10,2),
	
);

CREATE TABLE REQUEST (
 	CDREQUEST INT IDENTITY (1,1),
	DTREQUEST DATE,
	CDCUSTOMER INTEGER,
	DTDELIVER DATE,
	VLTOTAL NUMERIC(10,2)
);

CREATE TABLE CUSTOMER (
 	CDCUSTOMER INT IDENTITY (1,1),
	NMCUSTOMER VARCHAR(255),
	NRFONE NUMERIC,
	DSADRESS VARCHAR(255)

);

CREATE TABLE PRODUCT (

 	CDPRODUCT INT IDENTITY (1,1),
	NMPRODUCT VARCHAR(255),
	CDSUPPLIER INT,
	VLPRICE NUMERIC(10,2),
	QTSTOCK INTEGER
);

CREATE TABLE SUPPLIER (

 	CDSUPPLIER INT IDENTITY (1,1),
	NMSUPPLIER VARCHAR(255),
	NRFONE NUMERIC
);