USE DESAFIOSQL
SET DATEFORMAT dmy;

INSERT INTO REQUEST VALUES (
'31/01/2008',
(SELECT c.CDCUSTOMER FROM CUSTOMER as c WHERE c.NMCUSTOMER = 'Fabiano'),
'05/02/2008',
54.00
) 

select * from REQUEST