-- caso o enunciado correta seja I e J
BEGIN TRANSACTION
	UPDATE CUSTOMER SET NRFONE = 99879375 WHERE NMCUSTOMER = 'Fabiano' 
	SELECT * FROM CUSTOMER
ROLLBACK TRANSACTION
	SELECT * FROM CUSTOMER



-- caso o enunciado correta seja G e H

SELECT * FROM REQUEST, CUSTOMER;
DELETE FROM REQUEST;
DELETE FROM CUSTOMER;
SELECT * FROM REQUEST, CUSTOMER;