USE treinamento;
SET DATEFORMAT dmy;
SELECT c.NMCUSTOMER, r.DTREQUEST, CAST(r.VLTOTAL AS decimal (6,2)) as Total FROM CUSTOMER as c, REQUEST as r WHERE c.CDCUSTOMER = r.CDCUSTOMER AND r.DTREQUEST BETWEEN '01/06/2003' AND '31/07/2003';