use treinamento

SELECT c.NMCUSTOMER, p.NMPRODUCT, r.DTREQUEST, pr.QTAMOUNT, pr.VLUNITARY, (pr.QTAMOUNT * pr.VLUNITARY) as ValorTotal FROM CUSTOMER as c, PRODUCT as p, PRODUCTREQUEST as pr, REQUEST as r WHERE  c.CDCUSTOMER = r.CDCUSTOMER AND r.CDREQUEST = pr.CDREQUEST AND pr.CDPRODUCT = p.CDPRODUCT AND pr.QTAMOUNT > 500



SELECT * FROM PRODUCTREQUEST ORDER BY QTAMOUNT DESC
--não existem solicitações com mais de 10 produtos por pedido