use treinamento

SELECT c.NMCUSTOMER, p.NMPRODUCT, r.DTREQUEST, pr.QTAMOUNT, pr.VLUNITARY, r.VLTOTAL 
		FROM CUSTOMER as c, PRODUCT as p, PRODUCTREQUEST as pr, REQUEST as r 
		WHERE  c.CDCUSTOMER = r.CDCUSTOMER AND r.CDREQUEST = pr.CDREQUEST AND pr.CDPRODUCT = p.CDPRODUCT AND pr.QTAMOUNT > 500

-- ou

SELECT c.NMCUSTOMER, p.NMPRODUCT, r.DTREQUEST, pr.QTAMOUNT, pr.VLUNITARY, r.VLTOTAL 
		FROM CUSTOMER as c INNER JOIN REQUEST as r ON r.CDCUSTOMER = c.CDCUSTOMER
						   INNER JOIN PRODUCTREQUEST as pr ON r.CDREQUEST = pr.CDREQUEST
						   INNER JOIN PRODUCT as p ON p.CDPRODUCT = pr.CDPRODUCT AND pr.QTAMOUNT > 500

SELECT * FROM PRODUCTREQUEST ORDER BY QTAMOUNT DESC
--não existem solicitações com mais de 10 produtos por pedido