USE treinamento

SELECT c.NMCUSTOMER, p.NMPRODUCT, s.NMSUPPLIER, r.DTREQUEST, r.DTDELIVER, r.VLTOTAL as 'ValorTotal' -- Em duvida referente a qual preço o enunciado solicita
		FROM CUSTOMER as c INNER JOIN REQUEST as r ON c.CDCUSTOMER = r.CDCUSTOMER
						   INNER JOIN PRODUCTREQUEST as pr ON r.CDREQUEST = pr.CDREQUEST
						   INNER JOIN PRODUCT as p ON pr.CDPRODUCT = p.CDPRODUCT AND p.VLPRICE > 20
						   INNER JOIN SUPPLIER as s ON p.CDSUPPLIER = s.CDSUPPLIER AND s.IDFONE LIKE '(011)%'
